import { execFile } from "child_process";
import { promises as fs } from "fs";
import path from "path";
import { promisify } from "util";
import type { Express, Request, Response } from "express";
import { isSafeSvgMarkup } from "./src/utils/svg/svgSafety";

const execFileAsync = promisify(execFile);

const ASSET_DIR = path.join(process.cwd(), "src", "assets", "svg");
const NAME_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const MAX_BYTES = 512 * 1024;

/** Art at the top level belongs to no category yet, which is a legitimate state. */
const UNCATEGORISED = "uncategorised";

/** Dev only: a built app serves files it cannot write, and should not pretend otherwise. */
const isEditable = () => process.env.NODE_ENV !== "production";

/**
 * `id` and `category` become path segments, so they are the inputs that could
 * escape the folder. Both are pattern-checked and the result re-checked against
 * the resolved directory — belt and braces, because a traversal here writes
 * anywhere the server process can reach.
 */
function resolveAssetPath(id: string, category: string): string | null {
  if (!NAME_PATTERN.test(id) || id.length > 64) return null;
  if (category !== UNCATEGORISED && (!NAME_PATTERN.test(category) || category.length > 64)) {
    return null;
  }

  const dir = category === UNCATEGORISED ? ASSET_DIR : path.join(ASSET_DIR, category);
  const filePath = path.join(dir, `${id}.svg`);
  const withinRoot = path.resolve(filePath).startsWith(`${path.resolve(ASSET_DIR)}${path.sep}`);
  return withinRoot && path.dirname(path.resolve(filePath)) === path.resolve(dir) ? filePath : null;
}

interface AssetRecord {
  id: string;
  category: string;
  markup: string;
  /** File mtime, so the list can sort by what was worked on last. */
  modified: number;
}

/** One level deep, because a category of categories is a filing system, not a collection. */
async function readCollection(): Promise<AssetRecord[]> {
  const entries = await fs.readdir(ASSET_DIR, { withFileTypes: true });
  const found: { id: string; category: string; file: string }[] = [];

  for (const entry of entries) {
    if (entry.isFile() && entry.name.toLowerCase().endsWith(".svg")) {
      found.push({
        id: entry.name.replace(/\.svg$/i, ""),
        category: UNCATEGORISED,
        file: path.join(ASSET_DIR, entry.name),
      });
      continue;
    }
    if (!entry.isDirectory()) continue;

    const inner = await fs.readdir(path.join(ASSET_DIR, entry.name));
    for (const name of inner.filter((n) => n.toLowerCase().endsWith(".svg"))) {
      found.push({
        id: name.replace(/\.svg$/i, ""),
        category: entry.name,
        file: path.join(ASSET_DIR, entry.name, name),
      });
    }
  }

  const assets = await Promise.all(
    found.map(async (asset) => {
      const [markup, stat] = await Promise.all([
        fs.readFile(asset.file, "utf8"),
        fs.stat(asset.file),
      ]);
      return { id: asset.id, category: asset.category, markup, modified: stat.mtimeMs };
    }),
  );
  return assets.sort((a, b) => a.id.localeCompare(b.id));
}

/** The generated id union is regenerated by the same script the CLI uses — one generator, no drift. */
async function regenerateIds(): Promise<void> {
  await execFileAsync("node", [path.join(process.cwd(), "scripts", "generate-svg-ids.mjs")]);
}

/**
 * Read and write the SVG collection as files on disk.
 *
 * The collection is source, not user data: these routes edit the working tree,
 * which is exactly why they are refused outside development. What the browser
 * saves here is what the next `git status` shows and what a coding agent reads.
 */
export function registerSvgAssetRoutes(app: Express): void {
  app.get("/api/svg-assets", async (_req: Request, res: Response) => {
    try {
      res.json({ editable: isEditable(), assets: await readCollection() });
    } catch (error) {
      res.status(500).json({ error: `Could not read the collection: ${(error as Error).message}` });
    }
  });

  app.put("/api/svg-assets/:id", async (req: Request, res: Response) => {
    if (!isEditable()) {
      return res.status(403).json({ error: "The collection is only editable in development." });
    }

    const category =
      typeof req.body?.category === "string" && req.body.category.trim()
        ? req.body.category.trim()
        : UNCATEGORISED;
    const filePath = resolveAssetPath(req.params.id, category);
    if (!filePath) {
      return res.status(400).json({
        error:
          "Id and category must be lowercase-kebab-case — they become the filename and the folder.",
      });
    }

    const markup = typeof req.body?.markup === "string" ? req.body.markup.trim() : "";
    if (!markup) return res.status(400).json({ error: "No markup." });
    if (Buffer.byteLength(markup) > MAX_BYTES) {
      return res.status(413).json({ error: "Markup is larger than 512KB." });
    }
    // The same guard the browser applies, so the file on disk can never be
    // something the app would refuse to render.
    if (!isSafeSvgMarkup(markup)) {
      return res
        .status(400)
        .json({ error: "Markup must start with <svg> and carry no scripts, handlers, or embeds." });
    }

    try {
      // Ids are global, so the same id in another category is the same asset
      // being refiled — write the new home, then drop the old one. Doing it in
      // that order means a failure leaves a duplicate, never nothing.
      const existing = (await readCollection()).find((asset) => asset.id === req.params.id);

      await fs.mkdir(path.dirname(filePath), { recursive: true });
      await fs.writeFile(filePath, markup.endsWith("\n") ? markup : `${markup}\n`);

      if (existing && existing.category !== category) {
        const previous = resolveAssetPath(req.params.id, existing.category);
        if (previous) await fs.rm(previous, { force: true });
      }

      await regenerateIds();
      res.json({
        id: req.params.id,
        category,
        created: !existing,
        moved: Boolean(existing) && existing.category !== category,
      });
    } catch (error) {
      res.status(500).json({ error: `Could not save: ${(error as Error).message}` });
    }
  });

  /**
   * Rename or refile without touching the markup — both are the same operation
   * on disk, because the path carries both facts.
   */
  app.patch("/api/svg-assets/:id", async (req: Request, res: Response) => {
    if (!isEditable()) {
      return res.status(403).json({ error: "The collection is only editable in development." });
    }

    try {
      const assets = await readCollection();
      const existing = assets.find((asset) => asset.id === req.params.id);
      if (!existing) return res.status(404).json({ error: `No asset "${req.params.id}".` });

      const toId =
        typeof req.body?.toId === "string" && req.body.toId.trim()
          ? req.body.toId.trim()
          : existing.id;
      const category =
        typeof req.body?.category === "string" && req.body.category.trim()
          ? req.body.category.trim()
          : existing.category;

      const from = resolveAssetPath(existing.id, existing.category);
      const to = resolveAssetPath(toId, category);
      if (!from || !to) {
        return res.status(400).json({
          error:
            "Id and category must be lowercase-kebab-case — they become the filename and folder.",
        });
      }
      // Ids are global, so a rename onto a live id would silently eat that asset.
      if (toId !== existing.id && assets.some((asset) => asset.id === toId)) {
        return res.status(409).json({ error: `An asset with the id "${toId}" already exists.` });
      }

      if (from !== to) {
        await fs.mkdir(path.dirname(to), { recursive: true });
        await fs.rename(from, to);
        await regenerateIds();
      }
      res.json({ id: toId, category });
    } catch (error) {
      res.status(500).json({ error: `Could not move: ${(error as Error).message}` });
    }
  });

  app.delete("/api/svg-assets/:id", async (req: Request, res: Response) => {
    if (!isEditable()) {
      return res.status(403).json({ error: "The collection is only editable in development." });
    }

    try {
      const existing = (await readCollection()).find((asset) => asset.id === req.params.id);
      if (!existing) return res.status(404).json({ error: `No asset "${req.params.id}".` });

      const filePath = resolveAssetPath(existing.id, existing.category);
      if (!filePath) return res.status(400).json({ error: "Refusing to delete that path." });

      await fs.rm(filePath, { force: true });
      // A category folder with nothing left in it is noise in the tree.
      if (existing.category !== UNCATEGORISED) {
        const dir = path.join(ASSET_DIR, existing.category);
        const remaining = await fs.readdir(dir).catch(() => ["keep"]);
        if (remaining.length === 0) await fs.rmdir(dir).catch(() => undefined);
      }
      await regenerateIds();
      res.json({ id: existing.id });
    } catch (error) {
      res.status(500).json({ error: `Could not delete: ${(error as Error).message}` });
    }
  });
}
