// Generated by scripts/generate-svg-ids.mjs — do not edit.
// Add artwork by dropping a .svg into a category folder here, then run `npm run svg:ids`.

export const SVG_ASSET_IDS = [
  "apple",
  "counting-quest",
  "cube",
  "cylinder",
  "grape",
  "mango",
  "orange",
  "star",
  "ten-frame",
  "triangle",
] as const;

export type SvgAssetId = (typeof SVG_ASSET_IDS)[number];

/** Folder each asset lives in. "uncategorised" means it sits at the top level. */
export const SVG_ASSET_CATEGORIES: Record<string, string> = {
  "apple": "fruits",
  "counting-quest": "manipulatives",
  "cube": "shapes",
  "cylinder": "shapes",
  "grape": "fruits",
  "mango": "fruits",
  "orange": "fruits",
  "star": "shapes",
  "ten-frame": "manipulatives",
  "triangle": "shapes",
};

export const SVG_CATEGORIES = [
  "fruits",
  "manipulatives",
  "shapes",
] as const;
