/**
 * Writes the literal id union and the category map for the SVG collection.
 *
 * `import.meta.glob` finds the artwork at runtime, but its keys are only
 * `string` to TypeScript — so `<SvgAsset id="aple" />` would compile. This
 * turns the folder listing into const tuples, which makes a typo a build error
 * and gives the id autocomplete.
 *
 * Layout: one folder per category, `fruits/mango.svg`. Files sitting loose at
 * the top level are uncategorised, which is a legitimate state — art can land
 * first and be filed later.
 *
 * Runs automatically on `npm run dev` and `npm run build`; run `npm run
 * svg:ids` by hand after dropping a new file in while the dev server is up.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const DIR = path.resolve("src/assets/svg");
const OUT = path.join(DIR, "ids.ts");

export const UNCATEGORISED = "uncategorised";
const NAME_PATTERN = /^[a-z0-9]+(-[a-z0-9]+)*$/;

/** One level deep, because a category of categories is a filing system, not a collection. */
async function collect() {
  const entries = await readdir(DIR, { withFileTypes: true });
  const found = [];

  for (const entry of entries) {
    if (entry.isFile() && entry.name.toLowerCase().endsWith(".svg")) {
      found.push({ file: entry.name, id: entry.name.replace(/\.svg$/i, ""), category: UNCATEGORISED });
      continue;
    }
    if (!entry.isDirectory()) continue;

    const inner = await readdir(path.join(DIR, entry.name));
    for (const name of inner.filter((n) => n.toLowerCase().endsWith(".svg"))) {
      found.push({
        file: `${entry.name}/${name}`,
        id: name.replace(/\.svg$/i, ""),
        category: entry.name,
      });
    }
  }
  return found;
}

const assets = await collect();

// The name is the id, so a name that is not a clean id is a mistake to report
// now rather than a lookup that quietly misses later.
const badNames = assets.filter(
  (asset) => !NAME_PATTERN.test(asset.id) || (asset.category !== UNCATEGORISED && !NAME_PATTERN.test(asset.category)),
);
if (badNames.length > 0) {
  console.error(
    `Rename these to lowercase-kebab-case — file and folder names become ids and categories:\n  ${badNames
      .map((asset) => asset.file)
      .join("\n  ")}`,
  );
  process.exit(1);
}

// Ids are global, not per category: `<SvgAsset id="apple" />` names one asset,
// so the same basename in two categories is ambiguous rather than clever.
const byId = new Map();
for (const asset of assets) {
  const seen = byId.get(asset.id);
  if (seen) {
    console.error(
      `Two assets share the id "${asset.id}": ${seen.file} and ${asset.file}. Ids must be unique across categories.`,
    );
    process.exit(1);
  }
  byId.set(asset.id, asset);
}

const sorted = [...byId.values()].sort((a, b) => a.id.localeCompare(b.id));
const categories = [...new Set(sorted.map((asset) => asset.category))].sort();

const idBlock = sorted.length
  ? `export const SVG_ASSET_IDS = [\n${sorted.map((asset) => `  "${asset.id}",`).join("\n")}\n] as const;\n\nexport type SvgAssetId = (typeof SVG_ASSET_IDS)[number];\n`
  : `export const SVG_ASSET_IDS = [] as const;\n\n// No artwork yet — \`never\` would make every call site an error, so the id\n// stays open until the first file lands.\nexport type SvgAssetId = string;\n`;

const categoryBlock = `\n/** Folder each asset lives in. "${UNCATEGORISED}" means it sits at the top level. */\nexport const SVG_ASSET_CATEGORIES: Record<string, string> = {\n${sorted
  .map((asset) => `  "${asset.id}": "${asset.category}",`)
  .join("\n")}\n};\n\nexport const SVG_CATEGORIES = [\n${categories
  .map((category) => `  "${category}",`)
  .join("\n")}\n] as const;\n`;

const contents = `// Generated by scripts/generate-svg-ids.mjs — do not edit.\n// Add artwork by dropping a .svg into a category folder here, then run \`npm run svg:ids\`.\n\n${idBlock}${categoryBlock}`;

// Only write on a real change, so the dev server does not reload for nothing.
const existing = await readFile(OUT, "utf8").catch(() => null);
if (existing !== contents) {
  await writeFile(OUT, contents);
  console.log(
    `svg:ids — ${sorted.length} asset${sorted.length === 1 ? "" : "s"} in ${categories.length} categor${
      categories.length === 1 ? "y" : "ies"
    }`,
  );
}
